// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Search.POC.API.Domain.Entities;

#nullable disable

namespace Search.POC.API.Domain.Context
{
    public partial class PheonixDbContext : DbContext
    {
        public PheonixDbContext()
        {
        }

        public PheonixDbContext(DbContextOptions<PheonixDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Somast> Somast { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Somast>(entity =>
            {
                entity.Property(e => e.CclastFourDigits).IsUnicode(false);

                entity.Property(e => e.Custno).IsUnicode(false);

                entity.Property(e => e.Ponum).IsUnicode(false);

                entity.Property(e => e.Sono).IsUnicode(false);

                entity.Property(e => e.Sostat).IsUnicode(false);

                entity.Property(e => e.Sotype).IsUnicode(false);

                entity.Property(e => e.Source).IsUnicode(false);

                entity.Property(e => e.Terr).IsUnicode(false);

                entity.Property(e => e.WebReference).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}